export const IMAGES_PATH = process.env.NEXT_PUBLIC_IMAGES_PATH
export const ICONS_PATH = process.env.NEXT_PUBLIC_ICONS_PATH

export const PAGOPA_HOME = process.env.NEXT_PUBLIC_PAGOPA_HOME
export const PAGOPA_HELP_EMAIL = process.env.NEXT_PUBLIC_PAGOPA_HELP_EMAIL

export const INTEROP_UI_URL = process.env.NEXT_PUBLIC_INTEROP_UI_URL
export const SELF_CARE_ONBOARDING_INTEROP_URL =
  process.env.NEXT_PUBLIC_SELF_CARE_ONBOARDING_INTEROP_URL
export const INTEROP_GUIDE_BASE_URL = process.env.NEXT_PUBLIC_INTEROP_GUIDE_BASE_URL

export const INTEROP_ONBOARDING_GUIDE_URL = `${INTEROP_GUIDE_BASE_URL}/${process.env.NEXT_PUBLIC_INTEROP_ONBOARDING_GUIDE_PATH}`
export const INTEROP_INTRO_GUIDE_URL = `${INTEROP_GUIDE_BASE_URL}/${process.env.NEXT_PUBLIC_INTEROP_INTRO_GUIDE_PATH}`
export const INTEROP_E_SERVICE_GUIDE_URL = `${INTEROP_GUIDE_BASE_URL}/${process.env.NEXT_PUBLIC_INTEROP_E_SERVICE_GUIDE_PATH}`
export const INTEROP_DPO_FAQ_URL = `${INTEROP_GUIDE_BASE_URL}/${process.env.NEXT_PUBLIC_INTEROP_DPO_FAQ_PATH}`

export const ONETRUST_DOMAIN_SCRIPT_ID = process.env.NEXT_PUBLIC_ONETRUST_DOMAIN_SCRIPT_ID

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL as string
